FROM kgyrtkirk/hive-dev-box:latest

USER root

COPY tools/install_executor.bash /tools/
RUN /tools/install_executor.bash


COPY tools/install_executor2.bash /tools/
RUN /tools/install_executor2.bash

COPY etc/* /etc/
COPY bin/* /bin/

WORKDIR /home/jenkins
USER jenkins
ENTRYPOINT []
CMD ["bash"]
