FROM kgyrtkirk/hive-dev-box:latest

USER root

COPY tools/install_executor.bash /tools/
RUN /tools/install_executor.bash


COPY tools/install_executor2.bash /tools/
ARG UID=1000
RUN /tools/install_executor2.bash ${UID}

COPY etc/* /etc/
COPY bin/* /bin/

WORKDIR /home/jenkins
USER jenkins

COPY tools/docker_entrypoint.executor /.entrypoint
ENTRYPOINT ["/.entrypoint"]
CMD ["bash"]
