#!/bin/bash -e

# go home...
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

cmd=$1
[ "$cmd" != "" ] && shift
case "$cmd" in
	enter)
		./enter.bash "$@"
	;;
	run)
		./run.bash -d "$@"
		./enter.bash "$@"
	;;
	run0)
		./run.bash "$@"
	;;
	bash_completion)
		cat bashrc
	;;
	*)
		echo "usage: $0 run <new_container_name>"
		echo "usage: $0 enter <existing_container_name>"
		exit 1
	;;
esac
