#!/bin/bash --login

set -e

echo " * installing some basic stuff..."

sudo cp -rsf /hive-dev-box/etc/* /etc/
sudo cp -rsf /hive-dev-box/bin/* /bin/


/bin/sw tez
/bin/sw hadoop
/bin/sw hive
/bin/sw eclipse
/bin/sw maven


git clone --reference /reference/hive https://github.com/apache/hive hive
cd hive
git remote add kgyrtkirk git@github.com:kgyrtkirk/hive

cd ..

[ -d /toolbox/build ] && sudo dpkg -i /toolbox/build/distributions/*.deb

#reinit_metastore > /dev/null 2>&1
#echo "exitcode: $?"

cat /etc/motd
if [ -t 0 ];then
    export USER=`whoami`
    exec bash --login
else
    echo "non-interactive shell detected; waiting for the end of the world... "
    echo > /tmp/.empty
    exec tail -f /tmp/.empty
fi

