#!/bin/bash -e

# FIXME: consider setting
#Set hive.tez.container.size=3356;
#Set hive.tez.java.opts=-Xmx2g;
#conf set hive/hive-site hive.tez.container.size 3356
#conf set hive/hive-site hive.tez.java.opts -Xmx2g
# FIXME: scale up mem values?

#addgroup --gid 999 docker_access
#adduser dev docker_access

cd tmp
#apt-get install -y dnsutils wmctrl firefox-esr

cat >> ~dev/.bashrc << EOF
export HIVE_TEST_DOCKER_HOST="\`ip r | grep '^default'|cut -d ' ' -f 3\`"

[ -d /hive-dev-box/ ] && . /hive-dev-box/bashrc

if [ "\$DISPLAY" != "" ]; then
  export WID=\`xprop -root _NET_ACTIVE_WINDOW|cut -d ' ' -f5\`
fi

function urgent() { wmctrl -i -r \$WID   -b add,demands_attention; backburner \$HOSTNAME;}

EOF


/tools/build_cleanup
