#!/bin/bash -e

# FIXME: consider setting
#Set hive.tez.container.size=3356;
#Set hive.tez.java.opts=-Xmx2g;
#conf set hive/hive-site hive.tez.container.size 3356
#conf set hive/hive-site hive.tez.java.opts -Xmx2g
# FIXME: scale up mem values?

apt-get install -y patchutils

/tools/build_cleanup
