#!/bin/bash
set -e

sudo apt-get install -y proxychains4

cat << EOF | sudo dd of=/etc/proxychains4.conf
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks5 172.18.0.1 1080
EOF

/tools/build_cleanup
