#!/bin/bash -e

sudo apt install gnupg ca-certificates curl

curl -s https://repos.azul.com/azul-repo.key | sudo gpg --dearmor -o /usr/share/keyrings/azul.gpg

echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" | sudo tee /etc/apt/sources.list.d/zulu.list

#apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
#apt-add-repository 'deb http://repos.azulsystems.com/debian stable main'
apt-get update
#apt-cache search java
apt-get install -y zulu-8 zulu-11

#update-java-alternatives --set zulu-8-amd64

/tools/build_cleanup
