#!/bin/bash
set -e

chown jenkins /work

pwd
git clone -o postgres https://github.com/postgres/postgres
#pgx
#sudo -u dev sw maven
#sudo -u dev sw protobuf
#sudo -u dev sw thrift 0.16.0

#/tools/build_cleanup

