#!/bin/bash

sudo apt-get install -y libopengl0 sudo imagemagick wget nano  libegl1 libxkbcommon0 libglx0
cd /tmp
set -e
wget https://www.codeandweb.com/download/texturepacker/6.0.1/TexturePacker-6.0.1.deb
sudo dpkg -i TexturePacker-*deb
rm *deb
