#!/bin/bash -e

sudo apt-get install -y cmake  libssl-dev \
	krb5-multidev libkrb5-dev gdb \
		 libreadline-dev libz-dev bison flex bear ninja-build meson libipc-run-perl iproute2 gitsome clang-format-13 \
	valgrind linux-perf \
	python3-pyyaml-env-tag



type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
&& sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
&& sudo apt update \
&& sudo apt install gh -y

#export DEBUGINFOD_URLS="https://debuginfod.debian.net"

#sudo mkdir /usr/local/pg
#sudo chown dev /usr/local/pg
/tools/build_cleanup
#deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye main

cat >> ~dev/.bashrc << EOF

export PGDATA=/home/dev/pg/current/data
export PATH+=:/home/dev/pg/current/bin


EOF
